import numpy as np
np.set_printoptions(precision=6, suppress=True, linewidth=140)

S = np.load("S.npy")
T = np.load("T.npy")
R = np.load("R.npy")

def key(M, decimals=6):
    return tuple(np.round(M, decimals).flatten().view(float))

def generate_group(gens, max_size=1000):
    I3 = np.eye(3, dtype=complex)
    elems = {key(I3): I3}
    frontier = [I3]
    while frontier:
        new_frontier = []
        for M in frontier:
            for g in gens:
                N = g @ M
                k = key(N)
                if k not in elems:
                    elems[k] = N
                    new_frontier.append(N)
        frontier = new_frontier
        if len(elems) > max_size:
            raise RuntimeError("group too big / not closing")
    return list(elems.values())

G_SR = generate_group([S, R])
print("Group generated by <S,R> has order:", len(G_SR))

G_all = generate_group([S, T, R])
print("Group generated by <S,T,R> has order:", len(G_all))

G = G_all
np.save("group_elems.npy", np.array(G))

# element order
def order_of(M, maxord=20):
    I3 = np.eye(3, dtype=complex)
    P = M.copy()
    for k in range(1, maxord+1):
        if np.max(np.abs(P - I3)) < 1e-6:
            return k
        P = P @ M
    return None

orders = [order_of(M) for M in G]
from collections import Counter
print("Order distribution:", Counter(orders))
