# -*- coding: utf-8 -*-
r"""verify_triality_crystals.py — dynamics-register run for the two-register model
(TWO_REGISTER_MODEL_v0.1.md, missing corner of the table: the roof clock / the turner).

THE OBJECTS.  D4 = so(8) has THREE minuscule crystals, 8 vertices each — the
crystal avatars of the three shadows:
    B(w1)  vector      : weights +-e_i (i=1..4)
    B(w3)  half-spinor : weights (+-1/2,...,+-1/2), ODD  number of minus signs
    B(w4)  half-spinor : weights (+-1/2,...,+-1/2), EVEN number of minus signs
(CONVENTION, stated: Bourbaki D4 fundamental weights w3 = (1,1,1,-1)/2 [odd
spinor, "8s'"], w4 = (1,1,1,1)/2 [even spinor, "8s"].  Simple roots
a1 = e1-e2, a2 = e2-e3, a3 = e3-e4, a4 = e3+e4; node 2 = trivalent centre.)

Minuscule Kashiwara rule: f_i applies at weight mu iff <mu, a_i^vee> = 1
(all D4 roots same length, so <mu,a_i^vee> = (mu,a_i)); f_i(mu) = mu - a_i.

REGISTERED EXPECTATIONS (fail-first; each resolvable REFUTED at equal prominence):
  E1  triality sigma implements crystal isomorphisms cycling
      B(w1)->B(w3)->B(w4)->B(w1) with colors permuted by (1 3 4).
  E2  THE HEADLINE: the clock commutes with the turn —
      sigma o Psi = Psi o sigma on the 24-vertex disjoint union
      (Psi = rowmotion per crystal).  NOT automatic-by-definition.
  E3  AUDITOR'S REFUTABLE GUESS: the spiral operator S = sigma o Psi
      ("turn then tick") has an ORDER-18 CYCLE (3 x h = 18, echoing the
      E7 56-clock's order 18).  Report the true cycle type whatever it is.
  E4  THE FOLD: quotient of the 24 by sigma (8 orbits, colors folded
      {1,3,4} -> one, 2 -> 2) carries the G2 7-dim fundamental crystal
      PLUS a trivial piece (8 = 7 + 1).  Ground truth: G2's 7-crystal
      built independently from G2 Cartan data.

Rowmotion convention (matches Merkabit_crystal/verify_csp_27.py exactly):
crystal order = transitive closure of f-edges with the HIGHEST weight on TOP
(f-edges go DOWN); L = J(P), P = join-irreducibles; order ideals are DOWN-sets;
Psi(I) = down-ideal generated by the MINIMAL elements of the complement P \ I.

House rules: compute never assert; refutations at equal prominence; tiny
(24 vertices); pure Python + numpy.  Not RH/GRH; no physics; Rule 3 (no
identifications) in force.

Run:  python -X utf8 verify_triality_crystals.py
"""
import itertools, cmath
from collections import defaultdict, Counter
from fractions import Fraction
from math import gcd

import numpy as np

PASS_N = FAIL_N = 0
CHECK_NO = 0
def check(claim, ok, detail=""):
    global PASS_N, FAIL_N, CHECK_NO
    CHECK_NO += 1
    s = "PASS" if ok else "FAIL"
    if ok: PASS_N += 1
    else:  FAIL_N += 1
    print(f"[{s}] ({CHECK_NO:02d}) {claim}" + (f"  -> {detail}" if detail else ""))
    return ok

print("=" * 78)
print("TRIALITY x CRYSTALS — the D4 triple, the clock, the turn, the fold")
print("dynamics-register run for TWO_REGISTER_MODEL_v0.1 (2026-09-02)")
print("=" * 78)
print("""
REGISTERED EXPECTATIONS (logged before computation; fail-first):
  E1  sigma = crystal isomorphisms  B(w1)->B(w3)->B(w4)->B(w1), colors (1 3 4)
  E2  HEADLINE: sigma o Psi = Psi o sigma on the 24-vertex union
  E3  GUESS: spiral S = sigma o Psi contains an ORDER-18 cycle (3 x h)
  E4  FOLD: quotient by sigma = G2 7-crystal (+) trivial piece  (8 = 7 + 1)
Each may resolve REFUTED; the refutation is recorded at equal prominence.
""")

# ======================================================================
# 1. D4 data.  Weights kept in DOUBLED coordinates (exact integers).
# ======================================================================
ALPHA = {1: (1, -1, 0, 0), 2: (0, 1, -1, 0), 3: (0, 0, 1, -1), 4: (0, 0, 1, 1)}
COLORS = (1, 2, 3, 4)

def pairing(w2, i):
    """<mu, a_i^vee> for doubled weight w2 (= 2*mu).  All roots length^2 = 2,
    so <mu,a_i^vee> = (mu, a_i) = dot(w2, a_i)/2."""
    s = sum(w2[k] * ALPHA[i][k] for k in range(4))
    assert s % 2 == 0, "non-integral pairing"
    return s // 2

def f_op(w2, i):
    return tuple(w2[k] - 2 * ALPHA[i][k] for k in range(4))

def build_crystal(hw2):
    """Kashiwara lowering from the highest weight, minuscule rule."""
    V = {hw2}; E = []; frontier = [hw2]
    while frontier:
        v = frontier.pop()
        for i in COLORS:
            if pairing(v, i) == 1:
                w = f_op(v, i)
                E.append((v, i, w))
                if w not in V:
                    V.add(w); frontier.append(w)
    return V, E

HW2 = {1: (2, 0, 0, 0), 3: (1, 1, 1, -1), 4: (1, 1, 1, 1)}  # w1, w3, w4 doubled
CRYSTAL = {k: build_crystal(HW2[k]) for k in (1, 3, 4)}

def wname(w2):
    if all(c % 2 == 0 for c in w2):           # vector weight +-e_i
        for k in range(4):
            if w2[k] != 0:
                return f"{'+' if w2[k] > 0 else '-'}e{k+1}"
    return "(" + " ".join("+" if c > 0 else "-" for c in w2) + ")/2"

print("--- 1. the three minuscule crystals (Kashiwara lowering) " + "-" * 20)
for k in (1, 3, 4):
    V, E = CRYSTAL[k]
    check(f"B(w{k}): exactly 8 vertices", len(V) == 8, f"|V|={len(V)}, |E|={len(E)}")
    # connectivity (undirected)
    adj = defaultdict(set)
    for u, i, v in E:
        adj[u].add(v); adj[v].add(u)
    seen = set(); stack = [next(iter(V))]
    while stack:
        x = stack.pop()
        if x in seen: continue
        seen.add(x); stack.extend(adj[x])
    check(f"B(w{k}): connected", seen == V)
    check(f"B(w{k}): minuscule — all Dynkin labels in {{-1,0,1}}",
          all(pairing(v, i) in (-1, 0, 1) for v in V for i in COLORS))
# weight-set identities
V1, E1 = CRYSTAL[1]; V3, E3 = CRYSTAL[3]; V4, E4 = CRYSTAL[4]
check("B(w1) weights = {+-e_i}",
      V1 == {tuple(2*s*(1 if k == j else 0) for k in range(4))
             for j in range(4) for s in (1, -1)})
check("B(w3) weights = spinors with ODD  number of minus signs",
      V3 == {w for w in itertools.product((1, -1), repeat=4) if w.count(-1) % 2 == 1})
check("B(w4) weights = spinors with EVEN number of minus signs",
      V4 == {w for w in itertools.product((1, -1), repeat=4) if w.count(-1) % 2 == 0})
check("the three weight-sets are pairwise disjoint",
      not (V1 & V3) and not (V1 & V4) and not (V3 & V4))

print("\ncolored edge lists (f-edges, highest weight at top):")
for k in (1, 3, 4):
    _, E = CRYSTAL[k]
    print(f"  B(w{k}):")
    for u, i, v in sorted(E, key=lambda e: (-sum(e[0]), e[1])):
        print(f"    {wname(u):>12s}  -{i}->  {wname(v)}")

# ======================================================================
# 2. Triality sigma: 4x4 matrix in the e-basis (solved, exact), order 3.
# ======================================================================
print("\n--- 2. triality sigma: matrix, order 3, weight-set 3-cycle " + "-" * 17)
S_cols = np.array([ALPHA[1], ALPHA[2], ALPHA[3], ALPHA[4]], float).T
T_cols = np.array([ALPHA[3], ALPHA[2], ALPHA[4], ALPHA[1]], float).T
A_float = T_cols @ np.linalg.inv(S_cols)
A2 = np.rint(2 * A_float).astype(int)           # doubled matrix
check("2*sigma is an integer matrix (entries of sigma are half-integers)",
      np.max(np.abs(2 * A_float - A2)) < 1e-12,
      "sigma = (1/2) * " + str(A2.tolist()))
AF = [[Fraction(int(A2[r][c]), 2) for c in range(4)] for r in range(4)]  # exact

def matmulF(X, Y):
    return [[sum(X[r][k] * Y[k][c] for k in range(4)) for c in range(4)] for r in range(4)]
IDF = [[Fraction(1 if r == c else 0) for c in range(4)] for r in range(4)]
check("sigma alpha_1 = alpha_3, alpha_2 = alpha_2, alpha_3 -> alpha_4, alpha_4 -> alpha_1 (exact)",
      all([ [sum(AF[r][k] * ALPHA[i][k] for k in range(4)) for r in range(4)]
            == list(ALPHA[j]) for i, j in ((1, 3), (2, 2), (3, 4), (4, 1))]))
check("sigma^3 = identity (exact)", matmulF(matmulF(AF, AF), AF) == IDF)
ATF = [[AF[c][r] for c in range(4)] for r in range(4)]
check("sigma orthogonal (sigma^T sigma = I): preserves the form, hence pairings",
      matmulF(ATF, AF) == IDF)

def sigma(w2):
    out = tuple(sum(A2[r][k] * w2[k] for k in range(4)) for r in range(4))
    assert all(c % 2 == 0 for c in out), "sigma image not in doubled lattice"
    return tuple(c // 2 for c in out)

check("sigma(B(w1)) = B(w3)", {sigma(w) for w in V1} == V3)
check("sigma(B(w3)) = B(w4)", {sigma(w) for w in V3} == V4)
check("sigma(B(w4)) = B(w1)", {sigma(w) for w in V4} == V1)

# ======================================================================
# 3. E1: sigma is a crystal isomorphism cycling the three, colors (1 3 4).
# ======================================================================
print("\n--- 3. E1: sigma as crystal isomorphism, colors permuted by (1 3 4) " + "-" * 8)
RHO = {1: 3, 2: 2, 3: 4, 4: 1}
E1_ok = True
for a, b in ((1, 3), (3, 4), (4, 1)):
    Ea = CRYSTAL[a][1]; Eb = CRYSTAL[b][1]
    mapped = {(sigma(u), RHO[i], sigma(v)) for u, i, v in Ea}
    ok = mapped == set(Eb) and len(Ea) == len(Eb)
    E1_ok &= ok
    check(f"E1: edge-by-edge  B(w{a}) -> B(w{b}):  mu -f_i-> nu  iff  "
          f"sigma(mu) -f_{{rho(i)}}-> sigma(nu)", ok,
          f"{len(Ea)} edges <-> {len(Eb)} edges")
E1_RES = "PASS" if E1_ok else "REFUTED"
print(f"\n  ** E1 RESOLUTION: {E1_RES} — sigma "
      + ("IS" if E1_ok else "IS NOT") + " a crystal isomorphism cycling the three. **")

# ======================================================================
# 4. The clock: each crystal is a distributive lattice J(P); rowmotion Psi.
# ======================================================================
print("\n--- 4. the clock: J(P) structure and rowmotion per crystal " + "-" * 16)
print("  convention (= Merkabit_crystal/verify_csp_27.py): highest weight on TOP,")
print("  f-edges DOWN; ideals are down-sets; Psi(I) = down-ideal generated by the")
print("  minimal elements of the complement P \\ I.")

CRYS_DATA = {}   # k -> dict with below/above/P/ideal maps/Psi as vertex perm
for k in (1, 3, 4):
    V, E = CRYSTAL[k]
    children = defaultdict(set)                 # direct f-children (lower covers)
    for u, i, v in E:
        children[u].add(v)
    below = {}                                   # below[v] = {w : w <= v}, incl v
    def dfs(v, acc):
        acc.add(v)
        for w in children[v]:
            if w not in acc: dfs(w, acc)
    for v in V:
        acc = set(); dfs(v, acc); below[v] = acc
    above = {v: {u for u in V if v in below[u]} for v in V}
    tops = [v for v in V if len(above[v]) == 1]
    bots = [v for v in V if len(below[v]) == 1]
    check(f"B(w{k}): unique top and unique bottom", len(tops) == 1 and len(bots) == 1,
          f"top={wname(tops[0])}, bottom={wname(bots[0])}")
    # meets and joins exist for all pairs
    def unique_extreme(cands, dominates):
        hits = [z for z in cands if all(w in dominates[z] for w in cands)]
        return hits[0] if len(hits) == 1 else None
    lat_ok = True
    for x, y in itertools.combinations(V, 2):
        lb = below[x] & below[y]; ub = above[x] & above[y]
        if unique_extreme(lb, above) is None: lat_ok = False   # meet = max of lb
        if unique_extreme(ub, below) is None: lat_ok = False   # join = min of ub
    check(f"B(w{k}): lattice — every pair has a meet and a join", lat_ok)
    # join-irreducibles: exactly one lower cover (f-edges ARE covers: each step
    # subtracts one simple root, so path length = height gap; an edge has gap 1)
    P = [v for v in V if len(children[v]) == 1]
    check(f"B(w{k}): join-irreducibles |P| = 6", len(P) == 6,
          "P = {" + ", ".join(wname(p) for p in sorted(P, key=lambda w: -sum(w))) + "}")
    def leq(p, q): return p in below[q]
    ideal_of = {x: frozenset(p for p in P if leq(p, x)) for x in V}
    vert_of = {I: x for x, I in ideal_of.items()}
    # full ideal set of P by brute force (2^6 subsets)
    all_ideals = set()
    for r in range(len(P) + 1):
        for sub in itertools.combinations(P, r):
            s = set(sub)
            if all(q in s for p in s for q in P if leq(q, p)):
                all_ideals.add(frozenset(s))
    check(f"B(w{k}): Birkhoff — x -> I(x) is a bijection onto J(P) "
          f"(proves distributivity)", len(vert_of) == 8 and set(ideal_of.values()) == all_ideals,
          f"|J(P)| = {len(all_ideals)}")
    def downclose(Ss):
        return frozenset(q for q in P if any(leq(q, s) for s in Ss))
    def rowmotion(I):
        comp = [p for p in P if p not in I]
        mins = [p for p in comp if not any(q != p and leq(q, p) for q in comp)]
        return downclose(mins)
    Psi = {x: vert_of[rowmotion(ideal_of[x])] for x in V}
    check(f"B(w{k}): rowmotion is a bijection on the 8 states",
          set(Psi.values()) == V)
    CRYS_DATA[k] = dict(V=V, P=P, below=below, ideal_of=ideal_of, Psi=Psi)

def perm_orbits(perm, dom):
    seen = set(); orbs = []
    for x in dom:
        if x in seen: continue
        orb = []; y = x
        while y not in seen:
            seen.add(y); orb.append(y); y = perm[y]
        orbs.append(orb)
    return sorted(orbs, key=len, reverse=True)

def lcm_list(ns):
    o = 1
    for n in ns: o = o * n // gcd(o, n)
    return o

print("\n  rowmotion orbit tables (h(D4) = 6 is the expected scale):")
CSP_ALL = True
for k in (1, 3, 4):
    d = CRYS_DATA[k]
    orbs = perm_orbits(d["Psi"], sorted(d["V"]))
    ctype = [len(o) for o in orbs]
    order = lcm_list(ctype)
    print(f"  B(w{k}): Psi-orbit type {ctype}, order {order}")
    for o in orbs:
        print("      (" + " -> ".join(wname(x) for x in o) + ")")
    check(f"B(w{k}): measured rowmotion order = 6 = h(D4)", order == 6,
          f"cycle type {ctype}")
    # CSP against the rank generating function at zeta_order
    sizes = Counter(len(I) for I in d["ideal_of"].values())
    RGF = [sizes.get(r, 0) for r in range(max(sizes) + 1)]
    zeta = cmath.exp(2j * cmath.pi / order)
    csp_ok = True; details = []
    powmap = {x: x for x in d["V"]}
    for dd in range(order):
        fix = sum(1 for x in d["V"] if powmap[x] == x)
        val = sum(RGF[r] * zeta ** (dd * r) for r in range(len(RGF)))
        csp_ok &= abs(fix - val) < 1e-9
        details.append(f"d={dd}:{fix}|{val.real:+.2f}{val.imag:+.2f}i")
        powmap = {x: d["Psi"][powmap[x]] for x in d["V"]}
    CSP_ALL &= csp_ok
    check(f"B(w{k}): CSP — |Fix(Psi^d)| = RGF(zeta_{order}^d) for all d",
          csp_ok, f"RGF coeffs {RGF}; " + "  ".join(details))
print(f"\n  CSP verdict: {'CONFIRMED on all three crystals' if CSP_ALL else 'FAILED somewhere'}"
      f"  (RGF = 1+q+q^2+2q^3+q^4+q^5+q^6, palindromic, RGF(1)=8)")

# ======================================================================
# 5. E2 (HEADLINE): the clock commutes with the turn on the 24-vertex union.
# ======================================================================
print("\n--- 5. E2: sigma o Psi = Psi o sigma on the disjoint union " + "-" * 16)
UNION = [(k, x) for k in (1, 3, 4) for x in sorted(CRYS_DATA[k]["V"])]
def Psi_u(kx):
    k, x = kx
    return (k, CRYS_DATA[k]["Psi"][x])
def sigma_u(kx):
    k, x = kx
    return (RHO[k], sigma(x))          # crystal index cycles 1->3->4->1 too
# sigma as poset isomorphism (edge sets map to edge sets, colors aside): E1 gave it
pos_iso = all({(sigma(u), sigma(v)) for u, i, v in CRYSTAL[a][1]} ==
              {(u, v) for u, i, v in CRYSTAL[b][1]} for a, b in ((1, 3), (3, 4), (4, 1)))
check("sigma is a poset isomorphism between consecutive crystal orders", pos_iso)
E2_ok = all(sigma_u(Psi_u(kx)) == Psi_u(sigma_u(kx)) for kx in UNION)
check("E2: sigma(Psi(x)) = Psi(sigma(x)) for ALL 24 vertices", E2_ok)
E2_RES = "PASS" if E2_ok else "REFUTED"
print(f"\n  ** E2 RESOLUTION: {E2_RES} — the clock "
      + ("COMMUTES" if E2_ok else "DOES NOT COMMUTE") + " with the turn. **")
if E2_ok:
    print("     (content: sigma is a poset isomorphism AND the rowmotion convention")
    print("      is intrinsic to the poset — nothing basis- or labeling-dependent.)")

# ======================================================================
# 6. E3: the spiral clock S = sigma o Psi — cycle type; order-18 guess.
# ======================================================================
print("\n--- 6. E3: the spiral operator S = sigma o Psi ('turn then tick') " + "-" * 9)
if E2_ok:
    print("  note: E2 PASS means the two compositions coincide; S is unambiguous.")
S_map = {kx: Psi_u(sigma_u(kx)) for kx in UNION}          # turn, then tick
S_alt = {kx: sigma_u(Psi_u(kx)) for kx in UNION}          # tick, then turn
check("S well-defined: turn-then-tick = tick-then-turn (E2 again)", S_map == S_alt)
orbs = perm_orbits(S_map, UNION)
ctype = [len(o) for o in orbs]
order_S = lcm_list(ctype)
print(f"\n  SPIRAL CLOCK: cycle type {ctype}, order {order_S}")
for o in orbs:
    print("    (" + " -> ".join(f"w{k}:{wname(x)}" for k, x in o) + ")")
S3 = {kx: S_map[S_map[S_map[kx]]] for kx in UNION}
s3type = sorted((len(o) for o in perm_orbits(S3, UNION)), reverse=True)
print(f"  S^3 cycle type {s3type}  (S^3 = Psi^3 by E2: a fixed-point-free involution)")
has18 = 18 in ctype
E3_RES = "CONFIRMED" if has18 else "REFUTED"
check("E3 registered guess: an order-18 cycle appears in S", has18,
      f"true cycle type {ctype}, order {order_S}")
print(f"\n  ** E3 RESOLUTION: {E3_RES} — registered guess was 3 x h = 18; "
      f"measured order is {order_S}. **")
if not has18 and E2_ok:
    print("     why 18 was never available: E2 makes sigma and Psi COMMUTE, so")
    print("     ord(S) | lcm(ord(sigma), ord(Psi)) = lcm(3,6) = 6.  The E7 56-clock's")
    print("     18 = h(E7) is one clock's own order, not a clock-x-turn product.")

# ======================================================================
# 7. E4: the fold — quotient by sigma vs the G2 7-crystal (+) trivial.
# ======================================================================
print("\n--- 7. E4: the fold — sigma-quotient of the 24 vs G2 ground truth " + "-" * 9)
check("sigma is fixed-point-free on the 24-vertex union",
      all(sigma_u(kx) != kx for kx in UNION))
orb_of = {}
orbits3 = []
for kx in UNION:
    if kx in orb_of: continue
    o = [kx, sigma_u(kx), sigma_u(sigma_u(kx))]
    for y in o: orb_of[y] = len(orbits3)
    orbits3.append(o)
check("exactly 8 sigma-orbits, each of size 3",
      len(orbits3) == 8 and all(len(set(o)) == 3 for o in orbits3))
# name each orbit by its vector-crystal representative
rep = {}
for j, o in enumerate(orbits3):
    vec = [x for k, x in o if k == 1]
    rep[j] = wname(vec[0])
# fold colors: {1,3,4} -> 'a' (the size-3 orbit class), 2 -> 'b'
# CONVENTION (stated): folded color a := sigma-orbit {1,3,4}  <->  G2 node 1 (SHORT);
#                      folded color b := fixed node 2         <->  G2 node 2 (LONG).
FOLD = {1: "a", 2: "b", 3: "a", 4: "a"}
folded = {}
for k in (1, 3, 4):
    cnt = Counter()
    for u, i, v in CRYSTAL[k][1]:
        cnt[(orb_of[(k, u)], FOLD[i], orb_of[(k, v)])] += 1
    folded[k] = cnt
check("quotient well-defined: all three crystals fold to the SAME colored graph",
      folded[1] == folded[3] == folded[4])
Q = folded[1]
print("\n  QUOTIENT GRAPH (8 sigma-orbits, labelled by vector representative):")
for (ju, c, jv), m in sorted(Q.items(), key=lambda t: t[0][1]):
    print(f"    [{rep[ju]:>3s}]  -{c}->  [{rep[jv]:>3s}]" + (f"   (x{m})" if m > 1 else ""))
n_q_edges = sum(Q.values())
out_by_color = Counter()
for (ju, c, jv), m in Q.items():
    out_by_color[(ju, c)] += m
functional = all(m <= 1 for m in out_by_color.values())
print(f"  quotient: 8 vertices, {n_q_edges} edges "
      f"({sum(m for (j,c,v),m in Q.items() if c=='a')} of color a, "
      f"{sum(m for (j,c,v),m in Q.items() if c=='b')} of color b); "
      f"f_a functional: {'yes' if functional else 'NO'}")

# ---- G2 ground truth, built independently from G2 Cartan data --------
print("\n  G2 ground truth (independent build, root-basis coordinates, exact):")
# alpha1 SHORT (len^2=2), alpha2 LONG (len^2=6), (a1,a2) = -3  (Bourbaki G2)
G = [[Fraction(2), Fraction(-3)], [Fraction(-3), Fraction(6)]]
def ip(x, y):
    return sum(x[r] * G[r][c] * y[c] for r in range(2) for c in range(2))
def coA(i):   # <mu, alpha_i^vee>
    a = [(1, 0), (0, 1)][i - 1]
    la = ip(a, a)
    return lambda mu: 2 * ip(mu, a) / la
POSROOTS = [(1, 0), (0, 1), (1, 1), (2, 1), (3, 1), (3, 2)]
w1g, w2g = (2, 1), (3, 2)          # fundamental weights in root basis
rho = (5, 3)
dim = Fraction(1)
for a in POSROOTS:
    dim *= Fraction(ip((w1g[0] + rho[0], w1g[1] + rho[1]), a), ip(rho, a))
check("Weyl dimension formula: dim V(w1) for G2 = 7", dim == 7, f"dim = {dim}")
# weights of the 7: W-orbit of w1 (each mult 1, extreme-orbit) + {0} (mult 7-6=1)
def refl(i, mu):
    a = [(1, 0), (0, 1)][i - 1]
    c = coA(i)(mu)
    return (mu[0] - c * a[0], mu[1] - c * a[1])
orbit = {w1g}
frontier = [w1g]
while frontier:
    m = frontier.pop()
    for i in (1, 2):
        m2 = refl(i, m)
        m2 = (Fraction(m2[0]), Fraction(m2[1]))
        if m2 not in orbit:
            orbit.add(m2); frontier.append(m2)
orbit = {(int(a), int(b)) for a, b in orbit}
check("W(G2)-orbit of w1 = the 6 short roots", len(orbit) == 6
      and orbit == {(1, 0), (1, 1), (2, 1), (-1, 0), (-1, -1), (-2, -1)},
      f"orbit = {sorted(orbit)}")
WTS7 = sorted(orbit | {(0, 0)})
# crystal of the 7: weights multiplicity-free => edges are the alpha_i-strings
# (f_i joins consecutive weights of each maximal alpha_i-string; sl2 consistency
#  checked: the top of every string of length L has <mu,a_i^vee> = L-1)
edges7 = []
str_ok = True
for i in (1, 2):
    a = [(1, 0), (0, 1)][i - 1]
    tops = [m for m in WTS7 if (m[0] + a[0], m[1] + a[1]) not in WTS7]
    for t in tops:
        s = [t]
        while (s[-1][0] - a[0], s[-1][1] - a[1]) in WTS7:
            s.append((s[-1][0] - a[0], s[-1][1] - a[1]))
        if len(s) > 1:
            str_ok &= coA(i)(t) == len(s) - 1
            for u, v in zip(s, s[1:]):
                edges7.append((u, i, v))
check("all sl2-strings consistent (top label = string length - 1)", str_ok)
indeg = Counter(); outdeg = Counter()
for u, i, v in edges7:
    outdeg[u] += 1; indeg[v] += 1
top7 = [m for m in WTS7 if indeg[m] == 0]
chain_ok = (len(edges7) == 6 and len(top7) == 1
            and all(outdeg[m] <= 1 and indeg[m] <= 1 for m in WTS7))
colorseq = []
if chain_ok:
    x = top7[0]
    while outdeg[x]:
        u, i, v = next(e for e in edges7 if e[0] == x)
        colorseq.append(i); x = v
check("G2 7-crystal = a 7-vertex CHAIN, color sequence top->bottom = 1,2,1,1,2,1",
      chain_ok and colorseq == [1, 2, 1, 1, 2, 1], f"sequence = {colorseq}")

# ---- graph-level comparison: quotient  vs  7-chain (+) isolated vertex ----
print("\n  E4 graph-level comparison (quotient vs G2 7-crystal (+) trivial):")
tgt_v, tgt_e = 8, 6                      # 7-chain + isolated point
iso_v_quot = [j for j in rep if not any(ju == j or jv == j for (ju, c, jv) in Q)]
graph_match = (n_q_edges == tgt_e and len(iso_v_quot) == 1 and functional)
check("E4 (graph level): quotient graph = G2 7-chain (+) isolated vertex",
      graph_match,
      f"quotient has {n_q_edges} edges (target {tgt_e}), "
      f"{len(iso_v_quot)} isolated vertices (target 1), "
      f"f_a functional: {functional} (a crystal needs yes)")

# ---- weight-level comparison: project to the sigma-fixed plane -----------
print("\n  E4 weight-level comparison (projection onto the sigma-fixed plane):")
# fixed plane of sigma is spanned by  s0 = (a1+a3+a4)/3  (short)  and  a2 (long):
# (a2,a2)/(s0,s0) = 2/(2/3) = 3 and angle(s0,a2) = 150 deg  =>  a G2 root system.
s0vec = tuple(ALPHA[1][k] + ALPHA[3][k] + ALPHA[4][k] for k in range(4))  # 3*s0
len_ratio = Fraction(2 * 9, sum(c * c for c in s0vec))       # (a2,a2)/(s0,s0)
dot_s0_a2 = sum(s0vec[k] * ALPHA[2][k] for k in range(4))    # 3*(s0,a2)
cos2 = Fraction(dot_s0_a2 ** 2, sum(c * c for c in s0vec) * 2)  # cos^2 angle
check("sigma-fixed plane carries G2 root data: length ratio 3, angle 150 deg",
      len_ratio == 3 and cos2 == Fraction(3, 4) and dot_s0_a2 < 0,
      f"(a2,a2)/(s0,s0) = {len_ratio}, cos^2 = {cos2}, cos < 0")
def g2_labels(w2):
    """G2 Dynkin labels of the projection of mu to the fixed plane
    (orthogonal projection => pairings with fixed-plane roots unchanged)."""
    a1lab = sum(w2[k] * s0vec[k] for k in range(4))
    a2lab = sum(w2[k] * ALPHA[2][k] for k in range(4))
    assert a1lab % 2 == 0 and a2lab % 2 == 0
    return (a1lab // 2, a2lab // 2)
quot_labels = []
for j, o in enumerate(orbits3):
    k, x = next(kx for kx in o if kx[0] == 1)
    quot_labels.append((rep[j], g2_labels(x)))
gt_labels = sorted((int(coA(1)(m)), int(coA(2)(m))) for m in WTS7)
print("    orbit -> G2 label:  " + ",  ".join(f"[{r}]->{l}" for r, l in quot_labels))
weight_match = sorted(l for _, l in quot_labels) == sorted(gt_labels + [(0, 0)])
check("E4 (weight level): 8 orbit projections = weights of the G2 7 PLUS one",
      weight_match,
      "multiset = 7-crystal weights + extra (0,0): zero weight has multiplicity 2")
E4_RES = "PASS" if graph_match else "REFUTED (graph level)"
print(f"""
  ** E4 RESOLUTION: {E4_RES}. **
     What the quotient ACTUALLY is: the color-folded D4 VECTOR crystal —
     8 vertices in ONE component, {n_q_edges} edges, with a DIAMOND in the middle
     ([+e3] -a-> [+e4], [+e3] -a-> [-e4], both -a-> [-e3]): the folded operator
     f_a is NOT a partial function (two a-edges leave [+e3]), so the quotient
     is NOT a crystal graph of any type — in particular not G2's 7 (+) 1.
     The 7 (+) 1 lives ONE LEVEL DOWN, at the WEIGHT level: {'PASS' if weight_match else 'FAIL'} —
     the 8 orbits project onto the sigma-fixed (G2) plane exactly as the
     7-crystal's weights plus a second copy of weight zero (the trivial 1).
     [obs] the turn's fixed world IS G2 and the folded state count IS 7 + 1 —
     but as a character/weight statement, not as a crystal-graph quotient; the
     staircase's 7 reappears at the bottom of the turn one register down.""")

# ======================================================================
# 8. summary
# ======================================================================
print("=" * 78)
print(f"SUMMARY: {PASS_N} PASS / {FAIL_N} FAIL of {CHECK_NO} checks")
print(f"  E1 (sigma = crystal iso, colors (1 3 4))          : {E1_RES}")
print(f"  E2 (HEADLINE: clock commutes with turn)           : {E2_RES}")
print(f"  E3 (guess: order-18 spiral cycle)                 : {E3_RES}"
      f"  [measured: cycle type {ctype}, order {order_S}]")
print(f"  E4 (fold = G2 7-crystal (+) 1)                    : "
      f"REFUTED at graph level / VERIFIED at weight level (7 + 1 exactly)"
      if not graph_match else
      f"  E4 (fold = G2 7-crystal (+) 1)                    : PASS")
print("=" * 78)
print("Not RH/GRH; no physics; Rule 3 (no identifications) in force.")
print("First computed meeting of the two registers: the clock (rowmotion, dynamics)")
print("and the turn (triality, grammar footprint) COMMUTE on the D4 triple;")
print("their product is an order-6 spiral, not an order-18 one; the turn's fold")
print("is G2 with state count 7+1 at the weight level, while the graph-level")
print("quotient breaks crystal functionality (the diamond).  Computed, not asserted.")
