"""Free exploration (NOT sealed) -- IB's batch of 2026-09-07.
(1) His words X = ABAB^-1, Y = B^-1ABAB^-1AB, P = X^2, Q = XY on a (2,3,7) pair of PSL(2,7):
    do they give S4 (24), A4 (12), V4 = <P, QPQ^-1> (4), three conjugate C2's -- for EVERY such pair?
(2) His two 'channels' D(G,H) = classes lost - classes created by splitting, and
    dL = (c_nt(G) - c_nt(H))/pi: computed exactly on the chain; is D = pi*dL identically?
PSL(2,7) built as the group generated by x->x+1 and x->-1/x on P^1(F_7) (8 points).
"""
import itertools, math
from sympy.combinatorics import Permutation, PermutationGroup

INF = 7
def tomap(f):
    return Permutation([f(x) for x in range(8)])
def add1(x): return INF if x == INF else (x + 1) % 7
def neginv(x):
    if x == INF: return 0
    if x == 0: return INF
    return (-pow(x, -1, 7)) % 7
t, s = tomap(add1), tomap(neginv)
G = PermutationGroup([t, s])
assert G.order() == 168, G.order()
els = list(G.generate())
def order(g): return g.order()

# (1) all (2,3,7) generating pairs
inv = [g for g in els if order(g) == 2]
thr = [g for g in els if order(g) == 3]
pairs = [(a, b) for a in inv for b in thr if order(a * b) == 7 and PermutationGroup([a, b]).order() == 168]
print("involutions", len(inv), "order-3", len(thr), "(2,3,7) generating pairs", len(pairs))

def chain_from(A, B):
    # sympy multiplies left-to-right: (A*B) means apply A then B. IB's words are products of matrices;
    # to be safe we test both conventions and report if they differ.
    Bi = B ** -1
    X = A * B * A * Bi
    Y = Bi * A * B * A * Bi * A * B
    P = X ** 2
    Q = X * Y
    S4 = PermutationGroup([X, Y]); A4 = PermutationGroup([P, Q])
    V4 = PermutationGroup([P, Q * P * Q ** -1])
    C2s = [PermutationGroup([P]), PermutationGroup([Q * P * Q ** -1]), PermutationGroup([P * Q * P * Q ** -1])]
    return S4, A4, V4, C2s

orders = set()
for A, B in pairs:
    S4, A4, V4, C2s = chain_from(A, B)
    orders.add((S4.order(), A4.order(), V4.order(), tuple(c.order() for c in C2s),
                A4.is_normal(S4), V4.is_normal(A4),
                all(c.is_subgroup(V4) for c in C2s),
                len({frozenset(c.generate()) for c in C2s})))
print("over all pairs, (|S4|,|A4|,|V4|,C2 orders, A4 normal in S4, V4 normal in A4, C2s in V4, #distinct C2):")
for o in orders: print("   ", o)

# (2) class bookkeeping on one chain
A, B = pairs[0]
S4, A4, V4, C2s = chain_from(A, B)
C2 = C2s[0]; E = PermutationGroup([Permutation(7)])
chain = [("PSL(2,7)", G), ("S4", S4), ("A4", A4), ("V4", V4), ("C2", C2), ("{e}", E)]
def classes(H):
    return [frozenset(c) for c in H.conjugacy_classes()]
def c_nt(H): return len(classes(H)) - 1
print("\nnontrivial class counts:", [(n, c_nt(H)) for n, H in chain])
print("\ntransition | lost | created-by-splitting | D = lost-created | pi*dL = c_nt(G)-c_nt(H) | D == pi*dL")
for (n1, Gu), (n2, Hl) in zip(chain, chain[1:]):
    CG = [c for c in classes(Gu) if len(c) > 1 or next(iter(c)) != Permutation(7)]
    CH = [c for c in classes(Hl) if len(c) > 1 or next(iter(c)) != Permutation(7)]
    Hset = frozenset(Hl.generate())
    lost = sum(1 for c in CG if not (c & Hset))
    created = 0
    for c in CG:
        k = sum(1 for d in CH if d <= c)
        if k > 0: created += k - 1
    D = lost - created; piDL = c_nt(Gu) - c_nt(Hl)
    print("%-9s -> %-5s | %4d | %20d | %16d | %24d | %s" % (n1, n2, lost, created, D, piDL, D == piDL))
# the three C2's: one A4-orbit, normalizer V4 ?
z = C2.generators[0]
orbit = {tuple((g * z * g ** -1).array_form) for g in A4.generate()}
allC2 = {tuple(c.generators[0].array_form) for c in C2s}
norm = sum(1 for g in A4.generate() if g * z * g ** -1 == z)
print("\nA4-conjugates of C2^(1):", len(orbit), " = his three C2's:", orbit == allC2, " |N_A4(C2)| =", norm, "(= |V4|)")
# and the 14 V4's of PSL(2,7): every V4 = O2 of one of the 14 S4's; the three C2's of ANY V4 are one A4-orbit
V4s = {frozenset(H.generate()) for H in [PermutationGroup([u, v]) for u in inv for v in inv if u != v and u * v == v * u]}
print("V4 subgroups of PSL(2,7):", len(V4s))
